spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
logging.level.org.springframework.data.mongodb=${SPRING_DEBUG}


# Configuración de Correo Electrónico
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
# IMPORTANTE: No es tu contraseña normal, debes generar una "Contraseña de Aplicación" en la seguridad de Google
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRINT_MAIL_PROPERTIES_MAIL_STARTTLS_ENABLE}