spring.mongodb.uri=mongodb://mongo_db:27017/workflow_inteligente
logging.level.org.springframework.data.mongodb=DEBUG



# Configuración de Correo Electrónico
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eliaspumaclaure48@gmail.com
# IMPORTANTE: No es tu contraseña normal, debes generar una "Contraseña de Aplicación" en la seguridad de Google
spring.mail.password=hlzcdcrvuytsuhuw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true